In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Placement.csv')

In [4]:
df.head()

,cgpa,placement_exam_marks,placed
0,7.19,26.0,1
1,7.46,38.0,1
2,7.54,40.0,1
3,6.42,8.0,1
4,7.23,17.0,0


In [6]:


plt.scatter(df['cgpa'],df['package'])
plt.xlabel('CGPA')
plt.ylabel('Package(in lpa)')

KeyError: 'package'

In [7]:
X = df.iloc[:,0:1]
y = df.iloc[:,-1]

In [8]:
y

0      1
1      1
2      1
3      1
4      0
      ..
995    1
996    1
997    0
998    1
999    1
Name: placed, Length: 1000, dtype: int64

In [9]:
x

NameError: name 'x' is not defined

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)
LinearRegression()
X_test

,cgpa
37,8.51
726,7.93
846,6.99
295,6.02
924,6.85
...,...
839,6.44
810,7.14
930,6.94
616,7.09


In [11]:
y_test

37     1
726    0
846    0
295    0
924    1
      ..
839    1
810    1
930    1
616    1
809    1
Name: placed, Length: 200, dtype: int64

In [12]:
lr.predict(X_test.iloc[0].values.reshape(1,1))

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.49947742])

In [13]:
plt.scatter(df['cgpa'],df['package'])
plt.plot(X_train,lr.predict(X_train),color='red')
plt.xlabel('CGPA')
plt.ylabel('Package(in lpa)')

KeyError: 'package'

In [14]:
m = lr.coef_
b = lr.intercept_
# y = mx + b

m * 8.58 + b

array([0.50042494])

In [15]:
m * 9.5 + b

array([0.51287811])

In [16]:
m * 100 + b

array([1.73789081])